### ISSUE TITLE
SNI support missing?

### ISSUE THREAD

**Issue by quezacoatl** [igrigorik/em-http-request#274] opened 2014-09-09 08:35 UTC
I have not been able to recreate the problem for any other website, but for a CloudFront distribution using SNI only all requests fail. net/http works fine.

```
require 'em-http-request'

EM.run do
  conn = EventMachine::HttpRequest.new('https://api.stage.entrance.sonymobile.com')

  req = conn.get

  req.callback do |res|
    puts "body: #{res.response}"
  end

  req.errback do |err|
    puts "error: #{err.error}"
  end
end
```

Output will always be 'error: connection closed by server'.

**Comment by scsmith** [comment] 2015-04-24 17:26
I've added some very very crude support for SNI as a client in eventmachine/eventmachine#593. I'd love it if anyone interested here could give it a shot and see if it works for them. It's the first time I've written C/C++ for a number of years so be gentle ;-).

**Comment by quezacoatl** [comment] 2015-04-24 18:15
@scsmith I did get my code example to work with your code. Can you see if it works for you?

**Comment by scsmith** [comment] 2015-04-26 18:31
@quezacoatl Yep, works for me.

**Comment by The-Only79** [comment] 2015-06-04 08:33
How you doing 👌

I am here now ☝

**Comment by sodabrew** [comment] 2015-11-04 05:46
Thank you @scsmith I've landed your patch on eventmachine master, and EM 1.2.0 will include SNI functionality!

**Comment by igrigorik** [comment] 2015-12-20 19:15
@sodabrew do we have an ETA for when 1.2.0 will be available? 

Reviewing the code, it looks like for em-http all we need is an extra param: 

```
start_tls(:protocols => %w(tlsv1), :sni_hostname => 'example.com')
```

Does that look right?

**Comment by sodabrew** [comment] 2015-12-20 20:42
Yes! That's the idea... I don't have a solid ETA, something like a month or so.

**Comment by igrigorik** [comment] 2015-12-20 22:34
@sodabrew excellent. In theory, 6503ae8 should do the trick then. Please give it a try! :)

**Comment by jamesotron** [comment] 2016-05-23 04:31
I've just found this issue and it's not working for me. I'll dig into it and try and identify the cause of the issue (using EM 1.2.0.1).

**Comment by jamesotron** [comment] 2016-05-24 00:17
So I've been thinking about this for 24 hours or so and realise that the fix in https://github.com/igrigorik/em-http-request/commit/6503ae8c5e48ea553852afb4ddbb62a039dcce16 only addresses `https` connections, and not other SSL/TLS protocols (`wss` is one such example).  Should we just always set the `:sni_hostname` and leave it at that?

**Comment by igrigorik** [comment] 2017-06-25 18:19
@jamesotron apologies, missed this.. 

> Should we just always set the :sni_hostname and leave it at that?

Yes, and.. isn't that what 6503ae8 does? Sorry, may be missing context.. :)

**Comment by jamesotron** [comment] 2017-06-25 21:43
Yes. Looks like you're right.

**Comment by igrigorik** [comment] 2017-06-26 02:44
Cool.. In which case, anything left to do here, or are we good to close this?

**Comment by jamesotron** [comment] 2017-07-02 20:56
Looks to me like it can be closed.  Thanks.

**Comment by igrigorik** [comment] 2017-07-02 20:59
👍

**Closed by igrigorik** 2017-07-02 20:59 UTC
Labels: blocked
